services:
  web:
    network_mode: "host"
  celery_worker_three:
    build: .
    command: python -m celery -A web_grab worker -l info --loglevel=INFO --concurrency=1
    network_mode: "host"
    volumes:
      - .:/usr/src/app
  celery_worker_one:
    network_mode: "host"
  celery_worker_two:
    network_mode: "host"
