services:
  redis:
    image: "redis:7.0.11"
    command: redis-server
    ports:
      - "6380:6379"
  postgres:
    image: postgres:15.3
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5434:5432"
  web:
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started
  celery_worker_one:
    build: .
    command: python3 -m celery -A web_grab worker -l info --loglevel=INFO --concurrency=1 -n worker1@%h
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_started
  celery_worker_two:
    build: .
    command: python3 -m celery -A web_grab worker -l info --loglevel=INFO --concurrency=1 -n worker2@%h
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started
      celery_worker_one:
        condition: service_started
