services:
  postgres:
    image: postgres:15.3
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
  web:
    depends_on:
      postgres:
        condition: service_started
    extra_hosts:
      - "host.docker.internal:host-gateway"
  celery_worker_one:
    depends_on:
      postgres:
        condition: service_started
  celery_worker_two:
    depends_on:
      postgres:
        condition: service_started
