services:
  redis:
    image: "redis:7.0.11"
    command: redis-server
    ports:
      - "6379:6379"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_started
  celery_worker_one:
    build: .
    command: python -m celery -A web_grab worker -l info --loglevel=INFO --concurrency=1
    depends_on:
      redis:
        condition: service_started
  celery_worker_two:
    build: .
    command: python -m celery -A web_grab worker -l info --loglevel=INFO --concurrency=1
    depends_on:
      redis:
        condition: service_started
      celery_worker_one:
        condition: service_started
