services:
  web:
    network_mode: "host"
  celery_worker_three:
    build: .
    command: python -m celery -A web_grab worker -l info --loglevel=INFO --concurrency=1
    depends_on:
      redis:
        condition: service_started
