#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER docker WITH PASSWORD "$DOCKER_USER_PASSWORD";
	CREATE DATABASE docker;
    CREATE DATABASE web_grab;
	GRANT ALL PRIVILEGES ON DATABASE docker TO docker;
	GRANT ALL PRIVILEGES ON DATABASE web_grab TO docker;
EOSQL
