# Generated by Django 4.2.1 on 2023-06-12 11:01

from django.db import migrations, models
import grab_requests.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrabRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(auto_now=True)),
                ('site', models.CharField(max_length=255)),
                ('site_id', models.CharField(max_length=255)),
                ('xmltv_id', models.CharField(max_length=255)),
                ('result_xml', models.TextField(blank=True)),
                ('result_log', models.TextField(blank=True)),
                ('status', models.CharField(choices=[(grab_requests.models.RequestStatusEnum['PENDING'], 'PENDING'), (grab_requests.models.RequestStatusEnum['COMPLETE'], 'COMPLETE'), (grab_requests.models.RequestStatusEnum['ERROR'], 'ERROR')], default='PENDING', max_length=50)),
                ('channel_name', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
