# Generated by Django 4.2.1 on 2023-06-08 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrabRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(auto_now=True)),
                ('site', models.CharField()),
                ('site_id', models.CharField()),
                ('xmltv_id', models.CharField()),
                ('result_xml', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
