# Generated by Django 4.2.1 on 2023-06-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grab_requests', '0002_grabrequest_external_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrabSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(auto_now=True)),
                ('setting_name', models.CharField(max_length=255)),
                ('setting_value', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='grabrequest',
            name='icon_tag',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='grabrequest',
            name='offset',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
