# Generated by Django 4.2.1 on 2023-06-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grab_requests', '0003_grabsetting_grabrequest_icon_tag_grabrequest_offset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grabsetting',
            name='setting_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
