# Generated by Django 4.2.1 on 2023-06-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grab_requests', '0003_grabrequest_result_log_grabrequest_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grabrequest',
            name='site_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
