# Generated by Django 4.2.1 on 2023-06-12 09:11

from django.db import migrations, models
import grab_requests.models


class Migration(migrations.Migration):

    dependencies = [
        ('grab_requests', '0004_grabrequest_site_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grabrequest',
            name='status',
            field=models.CharField(choices=[(grab_requests.models.RequestStatusEnum['PENDING'], 'Pending'), (grab_requests.models.RequestStatusEnum['COMPLETE'], 'Complete'), (grab_requests.models.RequestStatusEnum['ERROR'], 'Error')], default='PENDING', max_length=50),
        ),
    ]
