# Generated by Django 4.2.1 on 2023-07-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grab_requests', '0004_alter_grabsetting_setting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grabrequest',
            name='icon_tag',
            field=models.TextField(blank=True, null=True),
        ),
    ]
