# Generated by Django 4.2.1 on 2023-06-12 10:21

from django.db import migrations, models
import grab_requests.models


class Migration(migrations.Migration):

    dependencies = [
        ('grab_requests', '0005_alter_grabrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grabrequest',
            name='status',
            field=models.CharField(choices=[(grab_requests.models.RequestStatusEnum['PENDING'], 'PENDING'), (grab_requests.models.RequestStatusEnum['COMPLETE'], 'COMPLETE'), (grab_requests.models.RequestStatusEnum['ERROR'], 'ERROR')], default='PENDING', max_length=50),
        ),
    ]
